FROM golang:1.22-bullseye

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    pkg-config \
    build-essential \
    libgtk-3-dev \
    libwebkit2gtk-4.0-dev \
    nodejs \
    npm

# Install Wails
RUN go install github.com/wailsapp/wails/v2/cmd/wails@latest

# Set working directory
WORKDIR /build

# Copy the project files
COPY . .

# Build the application
CMD wails build
